# Generated by Django 2.0.13 on 2019-06-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book_key',
            new_name='book',
        ),
    ]
